spring.application.name=runtrackerapp

spring.datasource.url=jdbc:postgresql://localhost:5432/running_tracker
spring.datasource.driver-class-name=org.postgresql.Driver
#database username and password
spring.datasource.username=postgres
spring.datasource.password=0968
#manages the database schema (DDL) based on your entity mappings when the SessionFactory is created.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

#for sending requests user
spring.security.user.name=sam
spring.security.user.password=1


